-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information
return {
	require "lua.custom.plugins.multicursor",
	require "lua.custom.plugins.autopairs",
	require "lua.custom.plugins.barbecue",
	require "lua.custom.plugins.crates",
	require "lua.custom.plugins.circom",
	require "lua.custom.plugins.cursorline",
	require "lua.custom.plugins.diffview",
	require "lua.custom.plugins.flash",
	require "lua.custom.plugins.git-blame",
	require "lua.custom.plugins.inlayhints",
	require "lua.custom.plugins.lazygit",
	require "lua.custom.plugins.lualine",
	require "lua.custom.plugins.markdown",
	require "lua.custom.plugins.multicursor",
	require "lua.custom.plugins.neogen",
	require "lua.custom.plugins.noice",
	require "lua.custom.plugins.oil",
	require "lua.custom.plugins.peek",
	require "lua.custom.plugins.rainbow-delimiters",
	require "lua.custom.plugins.rip-substitute",
	require "lua.custom.plugins.rustaceanvim",
	require "lua.custom.plugins.scrollbar",
	require "lua.custom.plugins.smart-splits",
	require "lua.custom.plugins.spectre",
	require "lua.custom.plugins.statuscol",
	require "lua.custom.plugins.symbol-usage",
	require "lua.custom.plugins.toggleterm",
	require "lua.custom.plugins.trouble",
	require "lua.custom.plugins.ts-context",
}
